name: Deploy Laravel to cPanel FTP

on:
  push:
    branches:
      - "main" # Ganti 'main' jika nama branch utama Anda 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      # PERUBAHAN DIMULAI DI SINI
      - name: Create .env file
        # Menjalankan perintah ini dari dalam folder 'backend'
        run: php -r "file_exists('.env.production') && copy('.env.production', '.env');"
        working-directory: ./backend

      - name: Install Composer Dependencies
        # Menjalankan composer dari dalam folder 'backend'
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
        working-directory: ./backend

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Hanya meng-upload isi dari folder 'backend'
          local-dir: ./backend/
          server-dir: ./