name: Deploy Laravel to cPanel SFTP

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Create .env file from secrets
        run: |
          echo "APP_NAME=EmerGo" >> .env
          echo "APP_ENV=production" >> .env
          echo "APP_KEY=" >> .env
          echo "APP_DEBUG=false" >> .env
          echo "APP_URL=https://faridfarhan.my.id" >> .env
          # ... (baris .env lainnya seperti sebelumnya)
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "CACHE_STORE=file" >> .env
          echo "QUEUE_CONNECTION=sync" >> .env
        working-directory: ./backend

      - name: Generate App Key
        run: php artisan key:generate --force
        working-directory: ./backend

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
        working-directory: ./backend
      - name: SFTP Deploy
        uses: laryve/sftp-deploy-action@v0.2.1
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22 
          path: /home/faridfar/public_html/backend/ # 
          local_path: ./backend/ 